//
//  ArticlesConfig.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticlesConfig: BaseConfig{
    func createModule(view: ArticlesViewController) {
        
        let interactor: ArticlesInteractor = ArticlesInteractor()
        let router: ArticlesRouter = ArticlesRouter()
        
        let presenter: ArticlesPresenter = ArticlesPresenter(view: view, interactor: interactor, router: router)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
