//
//  ArticlesProtocols.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol ArticlesViewProtocol: class {
    var presenter: ArticlesPresenterProtocol?  { get set }
    var articlesTableView: UITableView! { get set }
    func openSafari(url:URL)
}
//MARK: Presenter -
protocol ArticlesPresenterProtocol: class {
    var view: ArticlesViewProtocol?  { get set }
    func searchArticles(str:String)
    func loadDetails()
    func loadFavourites()
    func goToFavourites()
    
}

//MARK: Interactor -
protocol ArticlesInteractorOutputProtocol: class {

    func didFetchArticles()
    func didFailFetchArticles()
    func didSearchArticles()
    
}
protocol ArticlesInteractorInputProtocol: class {

  var presenter: ArticlesInteractorOutputProtocol?  { get set }
    
    func loadArticles()
    func loadFavourites()
    func searchArticles(str: String)
    func getArticles() -> [Articles]
    func getSearched() -> [Articles]
    func toggleFavourite(article:Articles)
    
}

//MARK: Router -
protocol ArticlesRouterProtocol: class {
    var view: UIViewController! { get set }
    func goToFavourites()
    
}
