//
//  ArticlesPresenter.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticlesPresenter: BasePresenter,ArticlesPresenterProtocol {

    weak internal var view: ArticlesViewProtocol?
    
    var interactor: ArticlesInteractorInputProtocol?
    
    private let router: ArticlesRouterProtocol

    init(view: ArticlesViewProtocol, interactor: ArticlesInteractorInputProtocol?, router: ArticlesRouterProtocol) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }
    func loadDetails() {
        self.baseView?.showLoadingIndicator()
        self.interactor?.loadArticles()
    }

}

extension ArticlesPresenter: ArticlesInteractorOutputProtocol {
    func didFetchArticles(articles: [Articles]) {
        self.baseView?.hideLoadingIndicator()
        
        self.
    }
    
    func didFailFetchArticles() {
        self.baseView?.hideLoadingIndicator()
    }
    
    
}
