//
//  ArticlesInteractor.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticlesInteractor: BaseInteractor<AppTarget>,ArticlesInteractorInputProtocol {
    
    weak var presenter: ArticlesInteractorOutputProtocol?
    func loadArticles() {
//        request(targetType: .signIn(email: email, pass: pass)) { (response: UserModel) in
//            UserDefaultsHandler().setLoggedIn(value: true)
//            if  let token = response.token {
//                UserDefaultsHandler().setUserToken(value: token)
//            }
//            UserDefaultsHandler().setUser(user: response)
//            self.presenter?.didBussLogin()
//        }
    }
    

}
