//
//  ArticlesProtocols.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol ArticlesViewProtocol: class {
    var presenter: ArticlesPresenterProtocol?  { get set }
}
//MARK: Presenter -
protocol ArticlesPresenterProtocol: class {
    var view: ArticlesViewProtocol?  { get set }

    func loadDetails()
}

//MARK: Interactor -
protocol ArticlesInteractorOutputProtocol: class {

  
}
protocol ArticlesInteractorInputProtocol: class {

  var presenter: ArticlesInteractorOutputProtocol?  { get set }
    
    func loadArticles()
}

//MARK: Router -
protocol ArticlesRouterProtocol: class {
    var view: UIViewController! { get set }
    
}
