//
//  ArticlesRouter.swift
//  NewsApp
//
//  Created Mena Gamal on 12/15/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ArticlesRouter: ArticlesRouterProtocol {
    
     var view: UIViewController!
    
  
}
