//
//  OnboardingConfig.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OnboardingConfig: BaseConfig{
    func createModule(view: OnboardingViewController,state: OnboardingState) {
        
        let interactor: OnboardingInteractor = OnboardingInteractor()
        let router: OnboardingRouter = OnboardingRouter()
        
        let presenter: OnboardingPresenter = OnboardingPresenter(view: view, interactor: interactor, router: router, state: state)
        
        router.view = view
        interactor.basePresenter = handleBasePresenter(baseView: view)
        view.presenter = presenter
        interactor.presenter = presenter
        presenter.baseView = view
    }
}
