//
//  OnboardingInteractor.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OnboardingInteractor: BaseInteractor<AppTarget>,OnboardingInteractorInputProtocol {

    weak var presenter: OnboardingInteractorOutputProtocol?
}
