//
//  OnboardingRouter.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OnboardingRouter: OnboardingRouterProtocol {
    
    
    var view: UIViewController!
    func goToNext() {
        
    }
    
    func goToHome() {
        
    }
    
    
}
