//
//  OnboardingInteractor.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OnboardingInteractor: BaseInteractor<AppTarget>,OnboardingInteractorInputProtocol {
    
    weak var presenter: OnboardingInteractorOutputProtocol?
    
    func saveCountry(code:String) {
        let defaults = UserDefaults.standard
        defaults.set(code, forKey: AppTargetConstant.UserDefaultsKeys.country)

    }
    
     func saveCategories(categories:[String]) {
        let defaults = UserDefaults.standard
        defaults.set(categories, forKey: AppTargetConstant.UserDefaultsKeys.categories)
    }
    
    
}
