//
//  OnboardingProtocols.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol OnboardingViewProtocol: class {
    var presenter: OnboardingPresenterProtocol?  { get set }
    var topicsCollections: UICollectionView! { get set }
    func loadCountriesLayout()
    func loadCategoriesLayout()
}
//MARK: Presenter -
protocol OnboardingPresenterProtocol: class {
    var view: OnboardingViewProtocol?  { get set }
    func loadDetails()
    func goToNextPage()  
}

//MARK: Interactor -
protocol OnboardingInteractorOutputProtocol: class {
    
}
protocol OnboardingInteractorInputProtocol: class {
    
    var presenter: OnboardingInteractorOutputProtocol?  { get set }
    func saveCountry(code:String)
    func saveCategories(categories:[String])
}

//MARK: Router -
protocol OnboardingRouterProtocol: class {
    var view: UIViewController! { get set }
    func goToNext()
    func goToHome()
    
}
