//
//  OnboardingProtocols.swift
//  NewsApp
//
//  Created Mena Gamal on 12/14/20.
//  Copyright © 2020 Mena Gamal. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: View -
protocol OnboardingViewProtocol: class {
    var presenter: OnboardingPresenterProtocol?  { get set }
}
//MARK: Presenter -
protocol OnboardingPresenterProtocol: class {
    var view: OnboardingViewProtocol?  { get set }
    func loadAllCountries()
    func loadAllCategories()
}

//MARK: Interactor -
protocol OnboardingInteractorOutputProtocol: class {
    
}
protocol OnboardingInteractorInputProtocol: class {

  var presenter: OnboardingInteractorOutputProtocol?  { get set }
    func loadAllCountries()
    func loadAllCategories()
}

//MARK: Router -
protocol OnboardingRouterProtocol: class {
    var view: UIViewController! { get set }
    
}
